5 due date and priority functionality
jecaps/ToDo-List-API pull request #13
Opened 2024-10-11 12:58 UTC by jecaps

- installed alembic 
- updated schemas and models
- implemented get_todos endpoint
- created todos_manager
- implemented sorting and filtering on todos
- updated the documentation

2024-10-13 17:08 UTC, akanz1 requested changes
great!

2024-10-13 17:08 UTC, akanz1 commented on README.md
> +        - order: Sort order (asd, desc)
```suggestion
        - order: Sort order (asc, desc)
```

2024-10-13 17:08 UTC, akanz1 commented on alembic/versions/1613c3341f78_add_due_date_and_priority_to_todos.py
> +    pass
no need for the pass statements here and in L.30

2024-10-13 17:08 UTC, akanz1 commented on app/todo_manager.py
> +from typing import List
use `list` instead of importing List from typing.

2024-10-14 07:48 UTC, jecaps commented
@akanz1

2024-10-14 08:30 UTC, akanz1 approved these changes

2024-10-15 13:30 UTC, merged